AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Smart Traffic Management System SAM template
Resources:
  StmsApi:
    Type: AWS::Serverless::Api
    Cors: '''*'''
    Properties:
      Description: Smart Traffic Management System API
      StageName: prod

  DecideTrafficLight:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.decide_traffic_light
      Runtime: python3.9
      CodeUri: functions/decide_traffic_light/
      Description: Making decisions for smart traffic light
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          DELIVERY_STREAM_NAME: PUT-S3-biItC
      Policies:
      - AWSLambdaBasicExecutionRole
      - AmazonKinesisFirehoseFullAccess
      Events:
        DecideTrafficLightApi:
          Type: Api
          Properties:
            Path: /decide-traffic-light
            Method: POST
            RestApiId:
              Ref: StmsApi

  DetectVehicles:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/stms:latest"
      MemorySize: 10240
      Timeout: 60
      Policies:
      - AWSLambdaBasicExecutionRole
      Events:
        DetectVehiclesApi:
          Type: Api
          Properties:
            Path: /detect-vehicles
            Method: POST
            RestApiId:
              Ref: StmsApi
