AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Smart Traffic Lights template
Resources:
  STLApi:
    Type: AWS::Serverless::Api
    Properties:
      Description: Smart Traffic Lights API
      Cors:
        AllowMethods: "'POST,GET,OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"
      StageName: Prod

  GetDashboardEmbedUrl:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.get_dashboard_embed_url
      Runtime: python3.9
      CodeUri: functions/get_dashboard_embed_url/
      Description: Get Quicksight dashboard embed url for web
      MemorySize: 128
      Timeout: 3
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - quicksight:GetDashboardEmbedUrl
                - quickSight:GetAnonymousUserEmbedUrl
              Resource:
                - arn:aws:quicksight:us-east-1:559497364474:dashboard/16c849b6-a3a1-48b4-aff4-7c736168a4c5
      Environment:
        Variables:
          AWS_ACCOUNT_ID: 559497364474
          DASHBOARD_ID: 16c849b6-a3a1-48b4-aff4-7c736168a4c5
      Events:
        GetDashboardEmbedUrlEvent:
          Type: Api
          Properties:
            Path: /dashboard-embed-url
            Method: GET
            RestApiId:
              Ref: STLApi

  DecideTrafficLight:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.decide_traffic_light
      Runtime: python3.9
      CodeUri: functions/decide_traffic_light/
      Description: Making decisions for smart traffic lights
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          DELIVERY_STREAM_NAME: smart-traffic-stream
      Policies:
      - AWSLambdaBasicExecutionRole
      - AmazonKinesisFirehoseFullAccess
      Events:
        DecideTrafficLightEvent:
          Type: Api
          Properties:
            Path: /decide-traffic-light
            Method: POST
            RestApiId:
              Ref: STLApi

  DetectVehicles:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Description: Detect vehicles based on YOLOv4 model
      ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/smart-traffic-lights:latest"
      MemorySize: 10240
      Timeout: 30
      Policies:
      - AWSLambdaBasicExecutionRole
      Events:
        DetectVehiclesEvent:
          Type: Api
          Properties:
            Path: /detect-vehicles
            Method: POST
            RestApiId:
              Ref: STLApi
