AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Smart Traffic Management System SAM template
Resources:
  StmsApi:
    Type: AWS::Serverless::Api
    Properties:
      Description: Smart Traffic Management System API
      Cors:
        AllowMethods: "'POST'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"
      StageName: Prod

  GetDashboardEmbedUrl:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.get_dashboard_embed_url
      Runtime: python3.9
      CodeUri: functions/get_dashboard_embed_url/
      Description: Get Quicksight dashboard embed url for web
      MemorySize: 128
      Timeout: 3
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - quicksight:GetDashboardEmbedUrl
                - quickSight:GetAnonymousUserEmbedUrl
              Resource:
                - arn:aws:quicksight:us-east-1:559497364474:dashboard/9a9d5d81-bc69-4c74-ac39-4eb34919ccca
      Environment:
        Variables:
          AWS_ACCOUNT_ID: 559497364474
      Events:
        GetDashboardEmbedUrlEvent:
          Type: Api
          Properties:
            Path: /dashboard-embed-url
            Method: GET
            RestApiId:
              Ref: StmsApi

  DecideTrafficLight:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.decide_traffic_light
      Runtime: python3.9
      CodeUri: functions/decide_traffic_light/
      Description: Making decisions for smart traffic light
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          DELIVERY_STREAM_NAME: smart-traffic-stream
      Policies:
      - AWSLambdaBasicExecutionRole
      - AmazonKinesisFirehoseFullAccess
      Events:
        DecideTrafficLightEvent:
          Type: Api
          Properties:
            Path: /decide-traffic-light
            Method: POST
            RestApiId:
              Ref: StmsApi

  DetectVehicles:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/stms:latest"
      MemorySize: 10240
      Timeout: 30
      Policies:
      - AWSLambdaBasicExecutionRole
      Events:
        DetectVehiclesEvent:
          Type: Api
          Properties:
            Path: /detect-vehicles
            Method: POST
            RestApiId:
              Ref: StmsApi
